version: '3.1'

services:
  mattermost:
    build: ./mattermost
    restart: always
    volumes:
      - ./mattermost/data/mattermost-data:/mm/mattermost-data
      - ./mattermost/data/mysql:/var/lib/mysql
    ports:
      - 8065:8065
    environment:
      - MYSQL_ROOT_PASSWORD=mostest
      - MYSQL_USER=mmuser
      - MYSQL_PASSWORD=mostest
